# Use official Node.js 22.14 Alpine as a base image
FROM node:22-slim
FROM satantime/puppeteer-node:20.9.0-bookworm

# Set the working directory inside the container
WORKDIR /app
# Copy package.json and package-lock.json (or yarn.lock) to the container
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code to the container
COPY . .

# Expose the port the app will run on
EXPOSE 8080

# Define the command to run the Express app
CMD ["npm", "run" , "dev"]
