# Use official Node.js 22.14 slim as a base image
FROM node:22-slim

# Set the working directory inside the container
WORKDIR /app-fe
# Copy package.json and package-lock.json (or yarn.lock) to the container
COPY package*.json ./

# Install dependencies
RUN npm install --production

RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object

# Copy the rest of the application code to the container
COPY . .

# Expose the port the app will run on
# EXPOSE 3000

# Define the command to run the Express app
CMD ["npm", "start"]
